name: Deploy to Forge Server

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 167.172.89.130
          username: forge
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/forge/canteen-central.on-forge.com
            git pull origin main
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear